---
# Brew packages
- name: Fetch brew packages
  homebrew: 
    name: ['fzf', 'bash-completion', 'curl', 'git', 'libplist', 'unrar', 'wget', 'node', 'doxygen', 'cmake']
    state: present
#Brew casks
- name: Fetch brew casks 
  homebrew_cask: name='p4v' state=present

- name: Install fzf
  command: /usr/local/opt/fzf/install
