---
# Brew packages
- name: Fetch brew packages
  homebrew: 
    name: ['fzf', 'bash-completion', 'curl', 'git', 'libplist', 'unrar', 'wget'] 
    state: present
#Brew casks
- name: Fetch brew casks 
  homebrew_cask: name='p4v' state=present
