---
# Brew packages
  - name: Fetch brew packages
    homebrew: name={{ item }} state=present
    with_items:
        - fzf
        - bash-completion
        - curl
        - docker
        - git
        - ideviceinstaller
        - libimobiledevice
        - libplist
        - unrar
        - wget

#Brew casks
  - name: Fetch brew casks
    homebrew_cask: name={{ item }} state=present
    with_items:
        - iterm2
        - p4merge
