---
# Brew packages
- name: Fetch brew packages
  homebrew:
    name: [ 'fzf', 'curl', 'git', 'libplist', 'unrar', 'wget', 'node', 'cmake' ]
    state: present
#Brew casks
- name: Fetch brew casks
  homebrew_cask: name='p4v' state=present

- name: Install fzf
  command: /usr/local/opt/fzf/install
